### ISSUE TITLE
Any chance of an .exe release?

### ISSUE THREAD

**Issue by ahmedelbahri** [soleon/Percentage#2]
Hey seleon,

First off, awesome job on the project—it looks really solid! I came across it on GitHub and wanted to give it a try. I was wondering if you’d consider putting out a .exe release? It’d make it a lot easier to get up and running without needing to build it locally.

Totally get it if that’s not on your radar, but I thought I’d ask. Thanks for sharing your work with the community—it’s much appreciated!

Cheers!

**Comment by joXXjo** [comment]
i am also a little confused. I installed this some time (i think 1 or two years) ago via Microsoft store, but now i can't find any installation, not in the store, not here. What's going wrong?

**Comment by ahmedelbahri** [comment]
it has been removed from the Microsoft store for some time, I managed to find an executable (.exe) file before but not anymore.
you can still go to the upstream repository (It's the main repository that this fork is based on), it has an executable (.exe) that works just fine, it shows the percentage in the navbar but that's it.

**Comment by ahmedelbahri** [comment]
the repository: https://github.com/kas/percentage
and the release: https://github.com/kas/percentage/releases/tag/1.2.0

**Comment by joXXjo** [comment]
Hey ahmedelbahri, 
thanks a lot, but this project from kas is not usable on my screen an there is a better alternative on the MS Store.
But the soleon percentage is  the best. It's so nice, so i can't understand why there is no way to get it.

**Comment by ahmedelbahri** [comment]
the .exe will not show any steps or anything once you click it twice you can go check on the taskbar for the percentage.

**Comment by ahmedelbahri** [comment]
it's not very pretty hhh
only  when it's not 100% and when it's not charging is when it's readable
you can check the forks as well
I did not like any except this one (props to the author) but you can check

**Comment by soleon** [comment]
Thanks for using my app guys.

I've just published a release of a self-contained portable version 2.0 of the app which now has nothing in common from the base branch I forked from https://github.com/kas/percentage.

New version is based on WPF-UI, uses native tray icon and a complete rebuilt of the fluent interface.

The app was removed from the Microsoft Store a few months ago due to missing a valid privacy policy link but I was way too busy to attend to the matter. My apologies for the inconvenience and confusion. I have setup the privacy policy page at https://soleon.github.io/Percentage/privacy-policy.htm.

The old version 1.3 of the app is not available in Microsoft Store again and this new 2.0 version is being certified for publication so it should be available in the Microsoft Store in a few days too.

Hope you guys enjoy the new version 😄

**Comment by soleon** [comment]
I thought sideloading an appx requires you to install the developer certificate on your own computer. 2.0 of the app has passed Microsoft certification, it should be available in Microsoft Store now. Otherwise, you can manually create a shortcut in the start menu startup folder:
`C:\Users\Username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`
