### ISSUE TITLE
Fix Tray Icon Position After Reboot

### ISSUE THREAD

**Issue by damndanielmusic** [soleon/Percentage#26]
Dear Developers,

first, thank you for your work on this nice add on. I noticed that after the rework, the position of the tray icon gets resetted after a reboot. I fix the tray Icon to be next to the WiFi symbol, but after a reboot it gets resetted to the hidden tray icons and I have to move it again next to the WiFi symbol, see two screenshots. Is there any way to fix this behaviour? Thank you very much.

![grafik](https://github.com/user-attachments/assets/7ea19d38-a1ce-48a3-a16c-fd2b72906207)

![grafik](https://github.com/user-attachments/assets/30c3a5e7-45ee-4411-a003-41778c7f4657)

**Comment by damndanielmusic** [comment]
Sorry, this might not be reboot related. At least I cannot reproduce this after a reboot anymore. Maybe it was because of the many updates recently, that the tray position got resetted.

**Comment by soleon** [comment]
@damndanielmusic thank you for your feedback.

I don't think the position of the tray icon can be controlled by the app itself. At least I'm not aware of a way to control this system behaviour. It is purely determined by the order when app starts one after another.

Closing this issue since it seems to be resolved.

**Comment by damndanielmusic** [comment]
Thank you for the response!
