### ISSUE TITLE
GDI+ error when setting tray icon if battery is full

### ISSUE THREAD

**Issue by WongMJ820** [soleon/Percentage#34]
<img width="799" alt="Screenshot 2024-12-26 150945" src="https://github.com/user-attachments/assets/24bd0bf5-b2b0-4b73-bfb9-9dc538e884e1" />
<img width="313" alt="Screenshot 2024-12-26 150925" src="https://github.com/user-attachments/assets/d6cf23b7-23e4-4733-a069-5c96c7b6eb26" />

**Comment by soleon** [comment]
Hi @WongMJ820 thank you for reporting this issue.

This error is fixed in version [2.1.4](https://github.com/soleon/Percentage/releases/tag/2.1.4) which is already available in Microsoft Store. Please update the app to the latest version to resolve this issue.

Closing this issue as it is duplicated with issue #25.
