### ISSUE TITLE
GDI+ error when updating the tray icon

### ISSUE THREAD

**Issue by sjia2s** [soleon/Percentage#8]
![image](https://github.com/user-attachments/assets/78cd4ee1-19c6-4a5b-b96f-b804e2dfea00)

I continually get this error message, in which the app crashes afterwards.

**Comment by soleon** [comment]
Hi @sjia2s thank you for reporting this issue.

I have some defensive updates in version 2.0.7, 2.0.8 and 2.0.9 to deal with potential cause of this issue, however, I'm still in the process of trying to identify what the root cause is.

Do you mind share how long you have set your refresh time to, and general system information including your Windows version, CPU model, graphics card model and any antivirus you are using?

Also, does the error happen right after launch the app, or as soon as the first refresh is triggered?

I'd also recommend try installing all available Windows updates, and make sure your graphics card is updated to the latest driver version.

**Comment by sjia2s** [comment]
Hi, thanks for replying to me. Here is the information you requested:

Refresh time: 1 second
OS: Windows 11 24H2 (I've just confirmed my Windows OS is up-to-date)
CPU: 13th Gen Intel(R) Core(TM) i5-1335U - 1.30 GHz
GPU: Intel(R) Iris(R) Xe Graphics

The app doesn't crash immediately nor on first refresh; rather, I get these error messages after about 20-30 minutes (very rough estimate, I will update you if I find that's inaccurate) after start.

Let me know if there's anything else you need.

**Comment by soleon** [comment]
@sjia2s I suspect that the error has something to do with using the 1 second refresh interval which can potentially cause a backpressure issue resulting in a lot of pending battery status refresh requests queued in memory and eventually causing the error.

Version [2.0.8](https://github.com/soleon/Percentage/releases/tag/2.0.8) has replaced the 1 second refresh interval with 5 seconds. It also has some defensive updates around this error. It is already available in the MS store now, and version [2.1.0](https://github.com/soleon/Percentage/releases/tag/2.1.0) with more defensive updates are also on the way to the store. Let me know if you are still seeing this error using 2.0.8.

**Comment by sjia2s** [comment]
@soleon I updated the app to version 2.1.0 this morning and so far it hasn't crashed once! I'll let you know if it does crash again, but so far I think this issue is solved. Thank you!
